 <h1 style="text-align: center; color: RED">NUMPY</h1> 

Numpy arrayleri liste veri yapılarına benzer. Ama onların aksine, farklı veri tiplerinde elemanlar içermez. Tek tip veri tipi içerir.

 <span style="color: blue; font-weight: bold;">Listelerden Array Oluşturmak</span> :

In [86]:
x = np.array([1,2,3,4])

In [88]:
x

array([1, 2, 3, 4])

In [90]:
type(x)

numpy.ndarray

In [95]:
y = np.array(['a','b','c'])

In [97]:
y

array(['a', 'b', 'c'], dtype='<U1')

In [99]:
#Bütün integerlar stringe dönüştürülecek
z = np.array([1,2,3,'a'])

In [102]:
z

array(['1', '2', '3', 'a'], dtype='<U11')

In [104]:
a = np.array([1,2,3,'5'])

In [106]:
a

array(['1', '2', '3', '5'], dtype='<U11')

In [108]:
#Bütün integerlar float dönüştürülür
b = np.array([1,2,3,4.5])

In [110]:
b

array([1. , 2. , 3. , 4.5])

 <span style="color: blue; font-weight: bold;">Array Data Tipini Manuel Belirlemek</span> :

In [114]:
x = np.array([1,2,3,4.6])

In [116]:
x

array([1. , 2. , 3. , 4.6])

In [118]:
x = np.array([1,2,3,4.6],dtype = 'int32')

In [120]:
x

array([1, 2, 3, 4])

In [122]:
x = np.array([1,2,3,4.6],dtype = 'str')

In [124]:
x

array(['1', '2', '3', '4.6'], dtype='<U3')

 <span style="color: blue; font-weight: bold;">Elemanları 0'lardan Oluşan Array Oluşturmak</span> :

In [128]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [130]:
np.zeros(10, dtype = str)

array(['', '', '', '', '', '', '', '', '', ''], dtype='<U1')

In [134]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [136]:
np.zeros(3,4)

TypeError: Cannot interpret '4' as a data type

In [138]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [142]:
np.zeros([3,8,8])

array([[[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0

In [144]:
np.zeros(2, dtype = int)

array([0, 0])

In [148]:
np.zeros((3,2), dtype = int)

array([[0, 0],
       [0, 0],
       [0, 0]])

In [150]:
np.zeros((3,2), dtype = bool)

array([[False, False],
       [False, False],
       [False, False]])

In [152]:
x=np.zeros([3,8,8,5])

In [154]:
x

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],



In [156]:
x.ndim

4

In [158]:
x.shape

(3, 8, 8, 5)

 <span style="color: blue; font-weight: bold;">Belirtilen Bir Elemandan Array Oluşturmak</span> :

In [196]:
np.full((4,5), 5)

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [198]:
np.full(4,5)

array([5, 5, 5, 5])

In [200]:
np.full((4,5),'a')

array([['a', 'a', 'a', 'a', 'a'],
       ['a', 'a', 'a', 'a', 'a'],
       ['a', 'a', 'a', 'a', 'a'],
       ['a', 'a', 'a', 'a', 'a']], dtype='<U1')

In [202]:
np.full((4,5),5.2, dtype=str)

array([['5', '5', '5', '5', '5'],
       ['5', '5', '5', '5', '5'],
       ['5', '5', '5', '5', '5'],
       ['5', '5', '5', '5', '5']], dtype='<U1')

 <span style="color: blue; font-weight: bold;">Ardışık Sayılardan Array Oluşturmak</span> :

In [206]:
np.arange(0,12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [208]:
np.arange(2,12)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [210]:
np.arange(2,12,2)

array([ 2,  4,  6,  8, 10])

In [212]:
np.arange(2,12,-2)

array([], dtype=int32)

In [214]:
np.arange(22,2,-2)

array([22, 20, 18, 16, 14, 12, 10,  8,  6,  4])

 <span style="color: blue; font-weight: bold;">Aralığı Eşit Uzaklıktaki Noktalara Bölmek</span> :

In [219]:
np.linspace(1,2)#defaul olarak 50 tane noktaya böler

array([1.        , 1.02040816, 1.04081633, 1.06122449, 1.08163265,
       1.10204082, 1.12244898, 1.14285714, 1.16326531, 1.18367347,
       1.20408163, 1.2244898 , 1.24489796, 1.26530612, 1.28571429,
       1.30612245, 1.32653061, 1.34693878, 1.36734694, 1.3877551 ,
       1.40816327, 1.42857143, 1.44897959, 1.46938776, 1.48979592,
       1.51020408, 1.53061224, 1.55102041, 1.57142857, 1.59183673,
       1.6122449 , 1.63265306, 1.65306122, 1.67346939, 1.69387755,
       1.71428571, 1.73469388, 1.75510204, 1.7755102 , 1.79591837,
       1.81632653, 1.83673469, 1.85714286, 1.87755102, 1.89795918,
       1.91836735, 1.93877551, 1.95918367, 1.97959184, 2.        ])

In [221]:
np.linspace(1,2,3)

array([1. , 1.5, 2. ])

In [223]:
np.linspace(1,2,3, endpoint = False)

array([1.        , 1.33333333, 1.66666667])

 <span style="color: blue; font-weight: bold;">Dağılımdan Array Oluşturmak</span> :

 (mean, std, array size)

In [230]:
np.random.normal(0, 1, (4,5))

array([[ 1.44453157, -0.65976088, -0.16007315,  0.74273555, -0.28192082],
       [ 0.31555787,  0.4524941 ,  1.1691801 , -0.33960559, -1.91697477],
       [-0.00949618,  0.34175015,  1.50924706, -0.23439524, -0.403767  ],
       [ 0.60272755, -1.1145284 ,  1.47188624, -0.99735405, -0.88483162]])

In [232]:
np.random.normal(0, 100, (4,5))

array([[ 19.38729418, -66.2329817 ,   2.54227912, 124.80920742,
        -51.26878556],
       [147.91483424, 115.10179737,  14.03404418,  14.62504241,
         41.49394254],
       [ 23.0395171 ,  72.29845567,  69.55331557, -91.40284643,
        103.64618678],
       [ 22.43711147, -71.02811943, -63.19721144, -29.21523134,
         55.91744936]])

 <span style="color: blue; font-weight: bold;">Random Integer'lar ile Array Oluşturmak</span> :

In [236]:
np.random.randint(1,10,(3,4))

array([[4, 2, 3, 8],
       [8, 5, 7, 2],
       [4, 4, 6, 3]])

In [238]:
np.random.randint(1,10,(3,5,5))

array([[[8, 1, 5, 2, 4],
        [7, 7, 8, 1, 6],
        [2, 4, 4, 3, 4],
        [5, 5, 1, 5, 1],
        [9, 6, 9, 9, 6]],

       [[7, 1, 3, 9, 6],
        [7, 5, 6, 6, 5],
        [8, 6, 6, 3, 1],
        [1, 2, 6, 3, 4],
        [2, 1, 4, 7, 5]],

       [[9, 6, 1, 4, 4],
        [5, 8, 8, 8, 3],
        [8, 1, 2, 6, 7],
        [8, 7, 3, 3, 4],
        [8, 5, 6, 2, 5]]])

In [240]:
np.random.randint(1,2)

1

In [244]:
d = {}
for _ in range(20000):
    val = np.random.randint(1,11)
    if val not in d:
        d[val] = 1
    else:
        d[val]+=1
print(d)

{10: 2020, 8: 2021, 9: 1915, 2: 1977, 4: 1951, 7: 2013, 5: 2014, 6: 1991, 3: 2057, 1: 2041}


 <span style="color: blue; font-weight: bold;">Birim Matrix Oluşturmak</span> :

In [248]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [250]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

 <h2 style="text-align: center; color: RED">ARRAY İŞLEMLERİ</h2>

In [258]:
x = np.array([1, 2, 3])
y = np.array([2, 4, 8])

x*y

array([ 2,  8, 24])

In [260]:
x = np.array([1, 2, 3])
y = np.array([2, 4, 8,12])

x*y

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [264]:
x = np.array([1, 2, 3])
y = np.array([2, 4, 8])

x+y

array([ 3,  6, 11])

In [292]:
x + y

ValueError: operands could not be broadcast together with shapes (2,3) (2,5,4) 

In [268]:
x * 3

array([3, 6, 9])

In [270]:
x = x*3

In [272]:
x

array([3, 6, 9])

 <h2 style="text-align: center; color: RED">ARRAY ÖZELLİKLERİ</h2>

 <span style="color: blue; font-weight: bold;">Shape</span> :

In [308]:
x = np.zeros((2,3))
x

array([[0., 0., 0.],
       [0., 0., 0.]])

In [284]:
x.shape

(2, 3)

In [286]:
y = np.zeros((2,5,4))

In [288]:
y.shape

(2, 5, 4)

 <span style="color: blue; font-weight: bold;">ndim</span> :

In [294]:
x.ndim

2

In [296]:
y.ndim

3

 <span style="color: blue; font-weight: bold;">size</span> :

In [300]:
x.size

6

In [302]:
y.size

40

<span style="color: blue; font-weight: bold;">dtype</span> :

In [306]:
x.dtype

dtype('float64')

<span style="color: blue; font-weight: bold;">Reshaping</span> :

In [312]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [314]:
a.ndim

1

In [316]:
a.size

10

In [320]:
a.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [322]:
a.reshape(2,5).ndim

2

In [324]:
a.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [326]:
a.reshape(5,3)

ValueError: cannot reshape array of size 10 into shape (5,3)

<span style="color: blue; font-weight: bold;">-1 ile Boyuta Karar Vermek</span> :

In [332]:
a.reshape(-1,2) # bir dimensionu ben belirlediğim diğerini o belirleyecek

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

<span style="color: blue; font-weight: bold;">Yeni Boyut Eklemek</span> :

In [336]:
a = np.arange(1,11)

In [338]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [342]:
a.shape

(10,)

In [346]:
b = a[np.newaxis,:]

In [348]:
b

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [350]:
b.shape

(1, 10)

In [352]:
c =  a[:, np.newaxis] #a[None,:] şeklinde de kullanabiliriz

In [354]:
c

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [356]:
c.shape

(10, 1)

<span style="color: blue; font-weight: bold;">Concatenation</span> :

In [360]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [364]:
np.concatenate([a,b])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [366]:
l = [10,11]
np.concatenate([a,b,l])

array([ 1,  2,  3,  4,  5,  6,  7,  8, 10, 11])

In [368]:
l = [10,11,'a']
np.concatenate([a,b,l]) #tüm elemanları str cevirdi

array(['1', '2', '3', '4', '5', '6', '7', '8', '10', '11', 'a'],
      dtype='<U11')

<span style="color: blue; font-weight: bold;">Stack</span> :

In [396]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [374]:
a.shape

(4,)

In [392]:
b.shape

(5,)

In [398]:
np.stack([a,b])#concanate'ten farkı yeni row ya da column oluşturması

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [388]:
xx= np.stack([a,b], axis=1)
xx

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [386]:
xx.shape

(4, 2)

<span style="color: blue; font-weight: bold;">Splitting</span> :

In [404]:
l = [10,20,30,40,50,60,70,80]

In [406]:
np.split(l,(2,6))

[array([10, 20]), array([30, 40, 50, 60]), array([70, 80])]

In [408]:
np.split(l,(3,7))

[array([10, 20, 30]), array([40, 50, 60, 70]), array([80])]

<span style="color: blue; font-weight: bold;">Splitin Sonucunu Birden Çok Değişkene Eşitleme</span> :

In [412]:
x, y, z = np.split(l,(2,6))

In [414]:
x

array([10, 20])

In [416]:
y

array([30, 40, 50, 60])

In [418]:
z

array([70, 80])

<span style="color: blue; font-weight: bold;">vsplit</span> :

In [429]:
a = np.arange(20).reshape(4,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [431]:
np.vsplit(a,[3])

[array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19]])]

In [433]:
np.vsplit(a,[1])

[array([[0, 1, 2, 3, 4]]),
 array([[ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])]

<span style="color: blue; font-weight: bold;">hsplit</span> :

In [439]:
np.hsplit(a,[2])

[array([[ 0,  1],
        [ 5,  6],
        [10, 11],
        [15, 16]]),
 array([[ 2,  3,  4],
        [ 7,  8,  9],
        [12, 13, 14],
        [17, 18, 19]])]

In [441]:
np.hsplit(a,[2])[0]

array([[ 0,  1],
       [ 5,  6],
       [10, 11],
       [15, 16]])

In [443]:
np.hsplit(a,[3])

[array([[ 0,  1,  2],
        [ 5,  6,  7],
        [10, 11, 12],
        [15, 16, 17]]),
 array([[ 3,  4],
        [ 8,  9],
        [13, 14],
        [18, 19]])]

In [445]:
a, b = np.hsplit(a,[3])

In [447]:
a

array([[ 0,  1,  2],
       [ 5,  6,  7],
       [10, 11, 12],
       [15, 16, 17]])

In [449]:
b

array([[ 3,  4],
       [ 8,  9],
       [13, 14],
       [18, 19]])

In [451]:
a=np.arange(20).reshape(5,4)

In [453]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [455]:
np.vsplit(a,[2,3])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19]])]

<span style="color: blue; font-weight: bold;">sorting</span> :

In [459]:
a = np.array([20,32,5,30,10])
a

array([20, 32,  5, 30, 10])

In [461]:
np.sort(a)

array([ 5, 10, 20, 30, 32])

In [ ]:
a.sort()#burda anın değeri güncellenir

<span style="color: blue; font-weight: bold;">argsort</span> :

In [465]:
idx = np.argsort(a)

In [467]:
idx# küçükten büyüğe sıralar ve o elemanların index numarasını döndürür

array([2, 4, 0, 3, 1], dtype=int64)

<span style="color: blue; font-weight: bold;">Multidimensional Array'lerde Indexleme</span> :

In [8]:
import numpy as np
a = np.arange(1,21).reshape(4,5)

In [10]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [12]:
a[0]

array([1, 2, 3, 4, 5])

In [14]:
a[0,0]

1

In [16]:
a[0][0]

1

In [18]:
a[1,1]

7

In [20]:
a[0,1]

2

In [22]:
a[1,1] = 10 #elemanı değiştirebilirim

In [24]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6, 10,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [26]:
a[1,1] = '30'

In [28]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6, 30,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [30]:
a[1,1] = 'a'

ValueError: invalid literal for int() with base 10: 'a'

<span style="color: blue; font-weight: bold;">Slice Indexing</span> :

In [34]:
a[0:3]

array([[ 1,  2,  3,  4,  5],
       [ 6, 30,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [36]:
a[:2]

array([[ 1,  2,  3,  4,  5],
       [ 6, 30,  8,  9, 10]])

In [38]:
a[::2]

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15]])

In [40]:
a[1::2]

array([[ 6, 30,  8,  9, 10],
       [16, 17, 18, 19, 20]])

In [44]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6, 30,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [42]:
a[:,3]

array([ 4,  9, 14, 19])

In [46]:
a[::2,3]

array([ 4, 14])

In [48]:
a[0,:]

array([1, 2, 3, 4, 5])

In [50]:
a[0,2:4]

array([3, 4])

In [52]:
a[:2,:3]

array([[ 1,  2,  3],
       [ 6, 30,  8]])

In [54]:
a[::,:4]

array([[ 1,  2,  3,  4],
       [ 6, 30,  8,  9],
       [11, 12, 13, 14],
       [16, 17, 18, 19]])

In [58]:
a[:,:4]

array([[ 1,  2,  3,  4],
       [ 6, 30,  8,  9],
       [11, 12, 13, 14],
       [16, 17, 18, 19]])

<span style="color: blue; font-weight: bold;">Fancy Index</span> :

In [62]:
x = np.arange(1,15)

In [64]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [66]:
idx = [4,5,7,11]
x[idx]

array([ 5,  6,  8, 12])

In [70]:
a = np.arange(12).reshape(3,4)

In [72]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [74]:
a[0:2,1]

array([1, 5])

In [76]:
a[0:2,1].shape

(2,)

In [78]:
a[0:2,1:3]

array([[1, 2],
       [5, 6]])

In [80]:
a[0:2,1:3].shape

(2, 2)

In [82]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [84]:
a[0,[1,3]]

array([1, 3])

In [86]:
a[0:,[1,3]]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [88]:
b = np.arange(20).reshape(4,5)

In [90]:
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [96]:
idx1= [1,3,2]
idx2= [3,0,2]

In [98]:
b[idx1,idx2]

array([ 8, 15, 12])

In [100]:
b[idx1][idx2]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [102]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [104]:
x[[1,2,3]] = 20

In [106]:
x

array([ 1, 20, 20, 20,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [108]:
x[[4,5,6]] = [100,200,300]

In [110]:
x

array([  1,  20,  20,  20, 100, 200, 300,   8,   9,  10,  11,  12,  13,
        14])

In [112]:
a=np.arange(1,13).reshape(3,4)

In [114]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [116]:
b=a[1,(1,3)]

In [120]:
b.shape

(2,)

<span style="color: blue; font-weight: bold;">Subarray</span> :

In [124]:
a = np.arange(1,21).reshape(4,5)

In [126]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [128]:
b = a[:2,:3]

In [130]:
b

array([[1, 2, 3],
       [6, 7, 8]])

In [132]:
b[0,0]=100

In [134]:
b

array([[100,   2,   3],
       [  6,   7,   8]])

In [136]:
a

array([[100,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20]])

In [138]:
a = np.arange(1,21).reshape(4,5)

In [140]:
b = a[:2,:3].copy()

In [142]:
b

array([[1, 2, 3],
       [6, 7, 8]])

In [144]:
b[0,0]=100
b

array([[100,   2,   3],
       [  6,   7,   8]])

In [146]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

<span style="color: blue; font-weight: bold;">Conditional Indexing</span> :

In [150]:
a = np.arange(1,10)

In [152]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [154]:
a < 5

array([ True,  True,  True,  True, False, False, False, False, False])

In [156]:
a[a<5]

array([1, 2, 3, 4])

In [164]:
b = np.array([2,3,3,4,5,61,7,8,11])

In [166]:
a == b

array([False, False,  True,  True,  True, False,  True,  True, False])

In [168]:
a[a==b]

array([3, 4, 5, 7, 8])

In [170]:
a[(a<3)| (a>5)] # or

array([1, 2, 6, 7, 8, 9])

In [174]:
a[(a<3) & (a>=5)]#and

array([], dtype=int32)

In [178]:
a[~((a<3) & (a>=5))]#değili demek istediğimizde tilda işaretini kullanırız

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

<span style="color: blue; font-weight: bold;">sum</span> :

In [182]:
a = np.arange(1,21).reshape(4,5)

In [184]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [186]:
np.sum(a)

210

In [188]:
np.sum(a[a < 5])

10

In [190]:
np.sum(a ,axis = 1)

array([15, 40, 65, 90])

In [192]:
np.sum(a ,axis = 0)

array([34, 38, 42, 46, 50])

In [194]:
a=np.arange(1,21).reshape(4,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [198]:
np.sum(a,axis=0).shape

(5,)

<span style="color: blue; font-weight: bold;">all</span> : Bütün elemanar şartı sağlıyor mu kontrol etmek

In [217]:
a = np.arange(20).reshape(4,5)

In [205]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [207]:
a > -1

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [209]:
np.all(a>-1)

True

In [211]:
a > 5

array([[False, False, False, False, False],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [213]:
np.all(a > 5)

False

In [215]:
np.all(a > 5, axis = 1)

array([False, False,  True,  True])

In [219]:
np.all(a > 5, axis = 0)

array([False, False, False, False, False])

In [221]:
a=np.arange(1,21).reshape(4,5)

In [223]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

<span style="color: blue; font-weight: bold;">any</span> : Herhangi bir eleman şartı sağlıyor mu kontrol etmek

In [227]:
a = np.arange(20).reshape(4,5)

In [229]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [231]:
np.any(a>17)

True

In [233]:
np.any(a>17, axis=1)

array([False, False, False,  True])

In [235]:
np.any(a>17, axis=0)

array([False, False, False,  True,  True])

In [237]:
a=np.arange(1,21).reshape(4,5)

In [239]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [241]:
np.any(a>4,axis=0) 

array([ True,  True,  True,  True,  True])